### ISSUE TITLE
Editing objects submitted to Interop

### ISSUE THREAD

**Issue by krishnans2006** [tj-uav/GroundStation#36]
SUAS 2022 Rules
> Objects which are created, submitted, and last edited during the team’s first flight will be
considered actionable.

Gray area on whether objects can be edited after submission - this is the only reference of any object editing in both the interop repository and rules.

This feature will not be implemented in [GroundStation](https://github.com/tj-uav/GroundStation), due to absence of interop server functionality.

**Comment by pizzalemon** [comment]
>Objects which are created, submitted, and last edited during the team’s first flight will be
considered actionable.

In my opinion, this says that it can be edited after submission. There's nothing explicitly barring it, so I would argue it's fine (and it's not one of those things that are blatantly wrong).

**Comment by krishnans2006** [comment]
> In my opinion, this says that it can be edited after submission. There's nothing explicitly barring it, so I would argue it's fine (and it's not one of those things that are blatantly wrong).

The problem, however, is that this feature is not supported anywhere in the AUVSI SUAS Interop repository. There are no functions or other ways to edit an ODLC. This is why it is tagged as a question.

**Comment by pizzalemon** [comment]
>The problem, however, is that this feature is not supported anywhere in the AUVSI SUAS Interop repository. 

Are you sure about this? I remember with the map question, you said the same thing, but it turned out to be there. I would like to know the answer for this because my implementation may change based on it.

**Comment by krishnans2006** [comment]
> I remember with the map question, you said the same thing, but it turned out to be there.

I don't remember this happening...

> Are you sure about this?

No, I am not sure, which is why I have not written any code for it. There *are* references to **PUT** functions within `auvsi_suas/client/client.py` for ODLCs and map images, but these may or may not be valid (as in, accepted by AUVSI SUAS during the competition), so I believe it would be best to create an Issue on the AUVSI SUAS interop repository.

**Comment by pizzalemon** [comment]
Closed due to Interop being discontinued.
