### ISSUE TITLE
Make frontend leaflet map run without internet

### ISSUE THREAD

**Issue by pizzalemon** [tj-uav/GroundStation#44]
All computers which run the Ground Station need to be connected to our router, which does not have access to the internet. The frontend leaflet map needs to have internet to run because it gets data from `osm.org`. This means that we need a way for the leaflet map to run without internet.

**Comment by krishnans2006** [comment]
Would we possibly be able to provide internet for the map through a hotspot? Or is this not possible given our current router configuration?

**Comment by krishnans2006** [comment]
Possibility: Downloading Map for offline use (can't zoom too far out?)

https://stackoverflow.com/questions/43608919/html-offline-map-with-local-tiles-via-leaflet
