### ISSUE TITLE
Frontend ODLC Submission Interface

### ISSUE THREAD

**Issue by pizzalemon** [tj-uav/GroundStation#46]
The frontend ODLC submission interface currently does not work. This is required for the AUVSI SUAS competition.

**Comment by krishnans2006** [comment]
Some requested features:
 - ODLCs automatically get rejected after 5 minutes of no review.
 - ODLC Images can be downloaded, edited, and re-uploaded to replace the existing image.
 - Maps can be uploaded on a separate tab, and one can be submitted to the Interop server.
