### ISSUE TITLE
Combine MAV and Interop Classes into an Application Class

### ISSUE THREAD

**Issue by krishnans2006** [tj-uav/GroundStation#47]

**Comment by pizzalemon** [comment]
They shouldn't necessarily be fully combined, by the way. The idea was to combine just some of the necessary stuff, such as general mission and Ground Station details.

**Comment by krishnans2006** [comment]
Oh - I was thinking of something similar to an adaptation: The Application class holds both the MAV and Interop Classes, and handles all requests to go to either class.
