### ISSUE TITLE
Fix Mission Points Map Display on Frontend.

### ISSUE THREAD

**Issue by pizzalemon** [tj-uav/GroundStation#91]
There's a lot of bugs - when you drag waypoints sometimes, the lines doesn't follow. Probably a billion errors I'm not thinking of, and another trillion I don't know of.

One specific error that is very strange is that insertion mode makes some of the waypoints transparent for no reason (including non-path waypoints, which is extremely strange). Because of how strange this error is, it may be something upstream.

**Comment by krishnans2006** [comment]
Done in #119 - there is still, however, a glitch that grays out the "Save waypoint button", which will be fixed shortly
