### ISSUE TITLE
Logs Page Restoration

### ISSUE THREAD

**Issue by pizzalemon** [tj-uav/GroundStation#92]
The logs page doesn't scroll properly. Also the autoscroll isn't very great - it's a toggle button currently, and it could be nicer, like a real autoscroll that scrolls when you're at the bottom of the page. Originally it was this, but I had to change it into the toggle button because I needed logs long list optimization, and there was not any time to complete such a feature right before AUVSI SUAS. Thus, it should properly implement this along side long list optimization.

**Comment by krishnans2006** [comment]
Done in #111
