### ISSUE TITLE
Path Planning (and Obstacle Avoidance)

### ISSUE THREAD

**Issue by pizzalemon** [tj-uav/GroundStation#94]
We don't get the mission waypoints until the actual flight. For AUVSI SUAS 2022 we didn't realize that, and had no path generation script ready, and so we were very confused during Interop testing when they gave us a sample path. A path needs to be generated by a script. Said path needs to be at least workable enough to be able to use at least a modified version of the path it generates. That is, the script should output something that we can modify (moderately, preferably slightly) to work.

The code should implement the following objectives in its routes, in this order:

1. Waypoints
2. UGV Drop
3. ODLC Search Grid
4. Mapping

Technically they do not need to be completed in that order (other than waypoints, which needs to be first), but that is the optimal order, really. Furthermore, obstacle avoidance needs to be baked into all the paths in this script.

**Comment by krishnans2006** [comment]
Done in #119, although still needs improvements for more complex waypoint types (jump, loiter, etc.).
