### ISSUE TITLE
Logs Page Data Fetching

### ISSUE THREAD

**Issue by pizzalemon** [tj-uav/GroundStation#97]
Like the submissions page, the logs page can end up getting way too much data that it wouldn't be able to store (React has a fixed variable size limit). This needs to be fixed, while also maintaining how the logs page already works, with the long list optimization, and the automatic scrolling.

**Comment by krishnans2006** [comment]
The current goal (as discussed with @JoshuaPikner) is now to in fact remove the logs tab, replacing it with a "View Log File" button and a small section displaying the most recent log messages. These will be persistent across tabs on the Flight Data page, so it won't be necessary to switch tabs to view logs.

**Comment by tjuav** [comment]
Resolved by @krishnans2006 in 6c198efb835195c78ce50a3b4e3815d6ee3293c1
